# @package _global_

defaults:
  - /default
  - _self_

data_dir: "/mnt/projects/prostate_cancer/cancer/Graz 400_rescaled"
sl_annotations_run_id: "e2109379e11640f481c2cb4c2c70a62b"
blacklist:
  - MUGGRZ-PATH-SCAN-SS7533-1110842
  - MUGGRZ-PATH-SCAN-SS7525-1018579
  - MUGGRZ-PATH-SCAN-SS7525-1018580
  - MUGGRZ-PATH-SCAN-SS7533-1110847
  - MUGGRZ-PATH-SCAN-SS7689-1014167
  - MUGGRZ-PATH-SCAN-SS7534-1108185
  - MUGGRZ-PATH-SCAN-SS7689-1014207
  - MUGGRZ-PATH-SCAN-SS7533-1113119
  - MUGGRZ-PATH-SCAN-SS7533-1113159
  - MUGGRZ-PATH-SCAN-SS7533-1110849
  - MUGGRZ-PATH-SCAN-SS7683-1017740
  - MUGGRZ-PATH-SCAN-SS7683-1017723

metadata:
  run_name: MUG 400 Data
  description: MUG 400 Data
