# @package _global_

defaults:
  - /default
  - _self_

full_metadata_csv_uri: "mlflow-artifacts:/97/6cb82d74735d413aa492548bbb6c20d6/artifacts/panda/slides_metadata.csv"

metadata:
  run_name: PANDA data
  description: PANDA data
