# @package _global_

defaults:
  - /default
  - _self_

# Points to the public mlflow
full_metadata_csv_uri: "mlflow-artifacts:/37/520a6e160a034073b5a03858840d4df2/artifacts/panda/slides_metadata.csv"

metadata:
  run_name: PANDA data
  description: PANDA data
