# @package _global_

defaults:
  - /default
  - _self_

full_metadata_csv_uri: "mlflow-artifacts:/97/dae25cd479f343f2ae7f292fd66215c3/artifacts/panda/slides_metadata.csv"

metadata:
  run_name: PANDA data
  description: PANDA data
