_target_: prostate_cancer.datamodule.datasets.LabeledTileEmbeddingsDataset
uris: ???
thresholds: ${thresholds}
embeddings_uri: ???
stratified_filter: ???
carcinoma_roi_t: ${thresholds.carcinoma_roi_t}