defaults:
  - base
  - _self_

tile_threshold: 0.5
slide_max_threshold: 0.5
slide_mpm_threshold: 0.5
slide_top_k_threshold: 0.5
slide_span_threshold: 0.5 # arbitrary - span predictions are binary

checkpoint: "mlflow-artifacts:/61/6fa19cb04c9f42289d044c2d60ba2987/artifacts/checkpoints/epoch=0-step=57820/checkpoint.ckpt"
public_checkpoint: "..."

model_name: "ResNet50 Stain (224x224)"
