defaults:
  - base
  - _self_

tile_threshold: 0.5
slide_max_threshold: 0.5
slide_mpm_threshold: 0.5
slide_top_k_threshold: 0.5
slide_span_threshold: 0.5 # arbitrary - span predictions are binary

checkpoint: "mlflow-artifacts:/61/3cfc9eaf98e44c63baedb74b6f38656e/artifacts/checkpoints/epoch=0-step=37512/checkpoint.ckpt"
public_checkpoint: "..."

model_name: "ResNet50 (224x224)"
