include:
  project: rationai/digital-pathology/templates/ci-templates
  file:
    - Python-Lint.gitlab-ci.yml
    - Kaniko.gitlab-ci.yml

build-image:
  extends:
    - .kaniko-build
  variables:
    DOCKERFILE_PATH: $CI_PROJECT_DIR/deployment/Dockerfile
    CI_REGISTRY_IMAGE: $CI_REGISTRY/rationai/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
    KANIKO_BUILD_CONTEXT: $CI_PROJECT_DIR/deployment
  rules:
    - if: "$CI_COMMIT_TAG"
    - when: manual

stages:
  - lint
