# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        args: [--unsafe]

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
         # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]
        args: [exp, build, chore, ci, docs, feat, fix, perf, refactor, revert, style, test]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      # Run the linter.
      - id: ruff
    #   Run the formatter.
      - id: ruff-format
