features:
  _target_: prostate_cancer.ml.nets.ResNet50
global_max_pooling:
  _target_: prostate_cancer.ml.nets.GMaxPool
classifier:
  _target_: prostate_cancer.ml.nets.BinaryClassifier
  input_dim: 2048
