defaults:
  - _self_
  - hydra: default

mlflow:
  tracking_uri: http://mlflow.rationai-mlflow:5000/

reporter:
  _target_: report.reporter.ReportAssembler
  template_asset_path: report_template.html
  save:
    # _target_: report.save.RunIDMLFlowReportAttacher
    # artifact_path: report.html
    # run_id: fa35edb93b104070ac2bfec5328eb86c
    _target_: report.save.MLFlowReportStorer
    artifact_path: report.html
    metadata:
        experiment_name: Testing
        run_name: "📊 XAI Callback Report Test"
        description: |
            This is a report containing test masks for select slides and store_numpy_gradients
        user: adambajger
  background:
    _target_: report.masks.ParquetSlideDatasetMLFlowMaskRetriever
    artifact_uris: 
      - "mlflow-artifacts:/65/0157ba4a0db349b8b86e4a24592d9230/artifacts/Prostate - test/"
    item_path_col: path
    ground_truth_col: carcinoma
    # _target_: report.masks.DriveMasksRetriever
    # dir_name: "/mnt/data/Projects/prostate_cancer/cancer/test_tiff"
    layer_name: HE
  title: NMF Clustering Heatmaps - Prostate
  mask_retrievers:
    # - _target_: report.masks.RunIDMlflowMaskRetriever
    #   run_id: fa35edb93b104070ac2bfec5328eb86c
    #   dir_name: LKCell/MOU
    #   shader_conf:
    #     type: classify
    #     classes: 5
    #     modifiable: true
    #     color: Turbo
    #   layer_name: LKCell
    # - _target_: report.masks.RunIDMlflowMaskRetriever
    #   layer_name: "Clusters NMF 6"
    #   run_id: c31d6d2acf8441cbac56170abc47c272
    #   dir_name: clustering_images
    #   shader_conf:
    #     type: classify
    #     classes: 7  # 1 for background (probably?)
    #     modifiable: true
    #     color: ['#000000', '#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b', '#e377c2', '#7f7f7f', '#bcbd22', '#17becf']
    # - _target_: report.masks.RunIDMlflowMaskRetriever
    #   layer_name: "0 - Clusters NMF 6"
    #   run_id: ad09fb84df0743858bc1025317a78be5
    #   dir_name: 'clustering_single_cluster_overlays/0'
    #   shader_conf:
    #     type: classify
    #     classes: 2
    #     modifiable: true
    #     color:  ['#000000', '#1f77b4']
    #     params: 
    #       connect: true
    # - _target_: report.masks.RunIDMlflowMaskRetriever
    #   layer_name: "1 - Clusters NMF 6"
    #   run_id: ad09fb84df0743858bc1025317a78be5
    #   dir_name: 'clustering_single_cluster_overlays/1'
    #   shader_conf:
    #     type: classify
    #     modifiable: true
    #     classes: 2
    #     color:  ['#000000', '#ff7f0e']
    #     params: 
    #       connect: true
    # - _target_: report.masks.RunIDMlflowMaskRetriever
    #   layer_name: "2 - Clusters NMF 6"
    #   run_id: ad09fb84df0743858bc1025317a78be5
    #   dir_name: 'clustering_single_cluster_overlays/2'
    #   shader_conf:
    #     type: classify
    #     modifiable: true
    #     classes: 2
    #     color:  ['#000000', '#2ca02c']
    #     params: 
    #       connect: true
    # - _target_: report.masks.RunIDMlflowMaskRetriever
    #   layer_name: "3 - Clusters NMF 6"
    #   run_id: ad09fb84df0743858bc1025317a78be5
    #   dir_name: 'clustering_single_cluster_overlays/3'
    #   shader_conf:
    #     type: classify
    #     modifiable: true
    #     classes: 2
    #     color:  ['#000000', '#d62728']
    #     params: 
    #       connect: true
    # - _target_: report.masks.RunIDMlflowMaskRetriever
    #   layer_name: "4 - Clusters NMF 6"
    #   run_id: ad09fb84df0743858bc1025317a78be5
    #   dir_name: 'clustering_single_cluster_overlays/4'
    #   shader_conf:
    #     type: classify
    #     modifiable: true
    #     classes: 2
    #     color:  ['#000000', '#9467bd']
    #     params: 
    #       connect: true
    # - _target_: report.masks.RunIDMlflowMaskRetriever
    #   layer_name: "5 - Clusters NMF 6"
    #   run_id: ad09fb84df0743858bc1025317a78be5
    #   dir_name: 'clustering_single_cluster_overlays/5'
    #   shader_conf:
    #     type: classify
    #     modifiable: true
    #     classes: 2
    #     color:  ['#000000', '#8c564b']
    #     params: 
    #       connect: true
    # ================================================
    # - _target_: report.masks.RunIDMlflowMaskRetriever
    #   layer_name: "0 - Clusters NMF 8"
    #   run_id: b96369edaff0463d9821a37c498a639c
    #   dir_name: 'clustering_single_cluster_overlays/0'
    #   shader_conf:
    #     type: heatmap
    #     color:  '#1f77b4'
    # - _target_: report.masks.RunIDMlflowMaskRetriever
    #   layer_name: "1 - Clusters NMF 8"
    #   run_id: b96369edaff0463d9821a37c498a639c
    #   dir_name: 'clustering_single_cluster_overlays/1'
    #   shader_conf:
    #     type: heatmap
    #     color:   '#ff7f0e'
    # - _target_: report.masks.RunIDMlflowMaskRetriever
    #   layer_name: "2 - Clusters NMF 8"
    #   run_id: b96369edaff0463d9821a37c498a639c
    #   dir_name: 'clustering_single_cluster_overlays/2'
    #   shader_conf:
    #     type: heatmap
    #     color:   '#2ca02c'
    # - _target_: report.masks.RunIDMlflowMaskRetriever
    #   layer_name: "3 - Clusters NMF 8"
    #   run_id: b96369edaff0463d9821a37c498a639c
    #   dir_name: 'clustering_single_cluster_overlays/3'
    #   shader_conf:
    #     type: heatmap
    #     color:  '#d62728'
    # - _target_: report.masks.RunIDMlflowMaskRetriever
    #   layer_name: "4 - Clusters NMF 8"
    #   run_id: b96369edaff0463d9821a37c498a639c
    #   dir_name: 'clustering_single_cluster_overlays/4'
    #   shader_conf:
    #     type: heatmap
    #     color:  '#9467bd'
    # - _target_: report.masks.RunIDMlflowMaskRetriever
    #   layer_name: "5 - Clusters NMF 8"
    #   run_id: b96369edaff0463d9821a37c498a639c
    #   dir_name: 'clustering_single_cluster_overlays/5'
    #   shader_conf:
    #     type: heatmap
    #     color:   '#8c564b'
    # - _target_: report.masks.RunIDMlflowMaskRetriever
    #   layer_name: "6 - Clusters NMF 8"
    #   run_id: b96369edaff0463d9821a37c498a639c
    #   dir_name: 'clustering_single_cluster_overlays/6'
    #   shader_conf:
    #     type: heatmap
    #     color:   '#e377c2'
    # - _target_: report.masks.RunIDMlflowMaskRetriever
    #   layer_name: "7 - Clusters NMF 8"
    #   run_id: b96369edaff0463d9821a37c498a639c
    #   dir_name: 'clustering_single_cluster_overlays/7'
    #   shader_conf:
    #     type: heatmap
    #     color:   '#7f7f7f'
    # =========================================
    # - _target_: report.masks.RunIDMlflowMaskRetriever
    #   layer_name: "Clusters NMF 8"
    #   run_id: 996592f936a0434dacfb65266f9bc55d
    #   dir_name: clustering_images
    #   shader_conf:
    #     type: classify
    #     classes: 9  # 1 for background (probably?)
    #     modifiable: true
    #     color: ['#000000', '#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b', '#e377c2', '#7f7f7f', '#bcbd22', '#17becf']
    # - _target_: report.masks.RunIDMlflowMaskRetriever
    #   layer_name: "Clusters NMF 4"
    #   run_id: f31187bc31714e9dab748a7919e6c7c8
    #   dir_name: clustering_images
    #   shader_conf:
    #     type: classify
    #     classes: 5  # 1 for background (probably?)
    #     modifiable: true
    #     color: ['#000000', '#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b', '#e377c2', '#7f7f7f', '#bcbd22', '#17becf']
    #     # color: ["#00000", "#6B00F5", "#324B47", "#3D324B", "#754B3B", "#A39753", "#2EA32E", "#2E55A3"]  #, "#B82E75", "#01F5CC", "#F54701", "#F5F201"]
    # - _target_: report.masks.RunIDMlflowMaskRetriever
    #   layer_name: "Clusters NMF 8 Segmentation"
    #   run_id: b96369edaff0463d9821a37c498a639c
    #   dir_name: clustering_images
    #   shader_conf:
    #     type: classify
    #     classes: 9  # 1 for background (probably?)
    #     modifiable: true
    #     color: ['#000000', '#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b', '#e377c2', '#7f7f7f', '#bcbd22', '#17becf']
    #     # color: ["#00000", "#6B00F5", "#324B47", "#3D324B", "#754B3B", "#A39753", "#2EA32E", "#2E55A3"]  #, "#B82E75", "#01F5CC", "#F54701", "#F5F201"]
    # - _target_: report.masks.RunIDMlflowMaskRetriever
    #   dir_name: test_cam
    #   run_id: 64e52667d20347be809d2b2be87ebd91
    #   layer_name: CAM
    #   shader_conf:
    #     type: bipolar-heatmap
    #     visible: true
    #     params:
    #       threshold: 30
    # - _target_: report.masks.ArtifactURIMasksRetriever
    #   artifact_uri: mlflow-artifacts:/24/6913a1e9d8304a28b8c4f5642bb8b5b6/artifacts/test_hirescam
    #   layer_name: HiResCAM
    #   shader_conf: classify-heatmap
    # - _target_: report.masks.DriveMasksRetriever
    #   dir_name: /mnt/data/rationai/data/home/bindas/annotations
    #   layer_name: Annotation
    #   shader_conf:
    #     type: edge
    # - _target_: report.masks.RunIDMlflowMaskRetriever
    #   run_id: 199141b76f90457fbf6183bd70a1e488
    #   dir_name: "annotation_masks/carcinoma/"
    #   layer_name: Annotation
    #   shader_conf:
    #     type: heatmap
    #     color:  
    #     - '#40f0f0'
    #     visible: 0
    - _target_: report.masks.RunIDMlflowMaskRetriever
      dir_name: tissue_masks
      run_id: 4ea7cee809a2443389855facba548959
      layer_name: "Tissue mask"
      shader_conf:
        type: heatmap
        visible: 0
    - _target_: report.masks.RunIDMlflowMaskRetriever
      dir_name: tif_cams
      run_id: 9fbe227016714097a6aeaaf698ac137c
      layer_name: "Bipolar GradCAM"
      shader_conf:
        type: bipolar-heatmap
        visible: 0
    # - _target_: report.masks.RunIDMlflowMaskRetriever
    #   dir_name: xai/gradcamraw
    #   run_id: b96369edaff0463d9821a37c498a639c
    #   layer_name: "Raw GradCAM heatmap"
    #   shader_conf:
    #     type: heatmap
    #     visible: 0
    # - _target_: report.masks.RunIDMlflowMaskRetriever
    #   dir_name: xai/gradcam
    #   run_id: b96369edaff0463d9821a37c498a639c
    #   layer_name: "GradCAM++"
    #   shader_conf:
    #     type: bipolar-heatmap
    #     visible: 0
    # - _target_: report.masks.DriveMasksRetriever
    #   layer_name: Clusters NMF 10
    #   dir_name: "/mnt/data/Projects/Explainability/XAICNNEmbeddings/VGG16_Prostate_NMF_10clusters/clustering_gray"
    #   shader_conf:
    #     type: classify
    #     classes: 11  # 1 for background (probably?)
    #     modifiable: true
    #     color: ["#00000", "#6B00F5", "#324B47", "#3D324B", "#754B3B", "#A39753", "#2EA32E", "#2E55A3", "#B82E75", "#01F5CC", "#F54701", "#F5F201"]

    # - _target_: report.masks.DriveMasksRetriever
    #   layer_name: Clusters NMF 4
    #   dir_name: "/mnt/data/Projects/Explainability/XAICNNEmbeddings/VGG16_Prostate_NMF_4clusters/clustering_color"
    #   shader_conf:
    #     type: identity
      