apiVersion: ray.io/v1
kind: RayService
metadata:
  name: rayservice-prostate-cancer
spec:
  serveConfigV2: |
    applications:
      - name: ProstateCancer
        import_path: app:app
        route_prefix: /

  rayClusterConfig:
    rayVersion: 2.24.0
    # enableInTreeAutoscaling: true
    # autoscalerOptions:
    #   idleTimeoutSeconds: 60 # number of seconds to wait before scaling down a worker pod which is not using Ray resources.
    #   securityContext:
    #     allowPrivilegeEscalation: false
    #     capabilities:
    #       drop: ["ALL"]
    #     runAsNonRoot: true
    #     seccompProfile:
    #       type: RuntimeDefault

    headGroupSpec:
      rayStartParams:
        dashboard-host: "0.0.0.0"
      template:
        spec:
          containers:
            - name: ray-head
              image: cerit.io/rationai/pathology/prostate-cancer:1.0.0
              imagePullPolicy: Always
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ["ALL"]
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
              resources:
                limits:
                  cpu: 4
                  memory: 6Gi
                requests:
                  cpu: 4
                  memory: 6Gi
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265 # Ray dashboard
                  name: dashboard
                - containerPort: 10001
                  name: client
                - containerPort: 8000
                  name: serve
              volumeMounts:
                - name: wsi-storage-pvc
                  mountPath: /data/Projects/empaia/job_slides
                  subPath: empaia/job_slides

          volumes:
            - name: wsi-storage-pvc
              persistentVolumeClaim:
                claimName: pvc-xopat3

    workerGroupSpecs:
      - groupName: cpu-group
        replicas: 1
        # minReplicas: 2
        # maxReplicas: 5
        rayStartParams: {}
        template:
          spec:
            containers:
              - name: ray-worker
                image: cerit.io/rationai/pathology/prostate-cancer:1.0.0
                imagePullPolicy: Always
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop: ["ALL"]
                  runAsNonRoot: true
                  seccompProfile:
                    type: RuntimeDefault
                lifecycle:
                  preStop:
                    exec:
                      command: ["/bin/sh", "-c", "ray stop"]
                resources:
                  limits:
                    cpu: 6
                    memory: 6Gi
                  requests:
                    cpu: 6
                    memory: 6Gi
                volumeMounts:
                  - name: wsi-storage-pvc
                    mountPath: /data/Projects/empaia/job_slides
                    subPath: empaia/job_slides

            volumes:
              - name: wsi-storage-pvc
                persistentVolumeClaim:
                  claimName: pvc-xopat3
