# @package _global_

test_size: ???
target_column: "carcinoma"

metadata:
  run_name: Data Split ${data.data_name}
  description: Data Split ${data.data_name}
  hyperparams:
    test_size: ${test_size}
