# @package _global_

request_timeout: 18000
max_concurrent: 5

qc_parameters:
  check_blur: True
  check_residual: True
  check_folding: True
  wb_correction: True
  subsample_masks: False

base_url: http://rayservice-qc-update-trial-serve-svc.rationai-jobs-ns.svc.cluster.local:8000/
output_path: ${prostate_cancer_artifacts}/qc_masks/${data.data_name}
use_case: QC Masks (v2)

metadata:
  hyperparams: ${qc_parameters}
