# @package _global_

request_timeout: 18000
max_concurrent: 5

qc_parameters:
  mask_level: 3
  sample_level: 1
  check_residual: True
  check_folding: False
  check_focus: True
  wb_correction: True
  store_masks_at_original_resolution: True

output_path: ${prostate_cancer_artifacts}/qc_masks/${data.data_name}
use_case: QC Masks (v2)

metadata:
  hyperparams: ${qc_parameters}
