# @package _global_

output_path: ${prostate_cancer_artifacts}/${data.data_name}_rescaled/${desired_mpp}
desired_mpp: ???
max_concurrent: 5

metadata:
  run_name: WSI resize ${data.data_name}
  description: WSI resize ${data.data_name}
  hyperparams:
    desired_mpp: ${desired_mpp}
