# @package _global_
defaults:
  - base
  - _self_

batch_size: 1024
output_path: ${prostate_cancer_artifacts}/tile_embeddings/${tile_encoder.name}/${data_name}

tile_encoder:
  _target_: ???
  name: ???

uris: ???

metadata:
  run_name: ${tile_encoder.name} Tile Embeddings ${data_name}
  description: ${tile_encoder.name} Tile Embeddings ${data_name}
  hyperparams:
    model: ${tile_encoder.name}
    output_path: ${output_path}
