# @package _global_

encoder: ???

output_path: ${carcinoma_artifacts}/tiles_with_embeddings/${encoder}/${data.data_name}
concurrency: 2048
block_size: 128
rows_per_file: 50000

start: null # index of slide in slides.parquet to start with (included)
end: null   # index of slide in slides.parquet to end with (included)

use_case: Tile Embeddings (V2)

metadata:
  hyperparams:
    encoder: ${encoder}
    concurrency: ${concurrency}
    block_size: ${block_size}
    rows_per_file: ${rows_per_file}
    start: ${start}
    end: ${end}
