# @package _global_

batch_size: 1024
output_path: ${prostate_cancer_artifacts}/tile_embeddings/${tile_encoder.name}/${data.data_name}

tile_encoder:
  _target_: ???
  name: ???

uris: ???
use_case: Tile Embeddings

metadata:
  hyperparams:
    model: ${tile_encoder.name}
    batch_size: ${batch_size}
