# @package _global_

mpp: 0.46
batch_size: 1024
tile_extent: ???
stride: ???
use_case: Tiling (v2)

overlapers: ??? # dict of objects for computing overlaps with masks

metadata:
  hyperparams:
    tile_extent: ${tile_extent}
    stride: ${stride}
    mpp: ${mpp}
