# @package _global_
defaults:
  - base
  - _self_

level: 3
max_concurrent: 100
output_path: ${prostate_cancer_artifacts}/tissue_masks/${data_name}

metadata:
  run_name: Tissue Masks ${data_name}
  description: Tissue Masks ${data_name}
