defaults:
  - decode_head: embedding_classifier
  - backbone: Virchow2
  - _self_

decode_head:
  in_features: 2560

_target_: prostate_cancer.cnn_model.FoundationProstateModel
lr: ???
tl_threshold: ???
freeze_backbone: True
