# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.loggers.mlflow.html#mlflow-logger
_target_: lightning.pytorch.loggers.MLFlowLogger
experiment_name: ${metadata.experiment_name}
run_name: ${metadata.run_name}
tracking_uri: file:./mlflow_store
tags:
  mlflow.note.content: ${metadata.description}
  mlflow.source.name: ${oc.env:HYDRA_SOURCE_TAG, unstaged}
