defaults:
  - hydra: default
  - logger: mlflow
  - _self_


prostate_cancer_artifacts: /mnt/projects/prostate_cancer/cancer
prostate_data: /mnt/data/MOU/

mmci_mpp: 0.23

data_name: ???

thresholds:
  tissue_roi_t: 0.5
  exclude_t: 0.0
  another_pathology_t: 0.0
  residual_t: 0.25
  blur_t: 0.25
  folding_t: 0.25

  carcinoma_roi_t: 0.5

metadata:
  experiment_name: Prostate
  run_name: ???
  description: ???
