defaults:
  - hydra: default
  - logger: mlflow
  - _self_


prostate_cancer_artifacts: /mnt/projects/prostate_cancer/cancer
prostate_data: /mnt/data/MOU/

thresholds: ???

metadata:
  experiment_name: Prostate
  run_name: ???
  description: ???
