defaults:
  - /default
  - _self_
  - /experiment: ???

mean: ???
std: ???

seed: ${random_seed:}
mode: ???

trainer:
  callbacks: ${callbacks}

metadata:
  run_name: ${model_name} ${use_case} ${data_name}
  description: ${model_name} ${use_case} ${data_name}
  hyperparams:
    batch_size: ${datamodule.batch_size}
    num_workers: ${datamodule.num_workers}
