defaults:
  - hydra: default
  - logger: mlflow
  - /preprocessing_stage: ??? # this specifies the preprocessing step to be done
  - _self_

prostate_cancer_path: /mnt/data/Projects/prostate_cancer/cancer

# CSV containing column "slide_path" (+ "carcinoma" label, and "case_id" for some stages)
slides_df_uri: ???
data_name: ??? # for mlflow run and data folder names
mmci_mpp: 0.23

# This tend to be general
thresholds:
  tissue_roi_t: 0.5
  exclude_t: 0.0
  another_pathology_t: 0.0
  residual_t: 0.25
  blur_t: 0.25
  folding_t: 0.25

metadata:
  experiment_name: Prostate
  run_name: ???
  description: ???
