defaults:
  - hydra: default
  - logger: mlflow
  - _self_


# Working directory for MMCI (Masaryk Memorial Cancer Institute) data
prostate_cancer_path: /mnt/data/Projects/prostate_cancer/cancer

# Paths to the slides (MRXS format) and annotations
data_path: /mnt/data/Projects/Data/MOU/prostate/tile_level_annotations
test_data_path: /mnt/data/Projects/Data/MOU/prostate/tile_level_annotations_test


# Microns per pixel of MMCI data on highest resolution
mmci_mpp: 0.23

tile_masks:
  output_path: ${prostate_cancer_path}/tile_masks
  max_concurrent: 5
  tile_uris:
    - "mlflow-artifacts:/65/0157ba4a0db349b8b86e4a24592d9230/artifacts/Prostate - train"
    - "mlflow-artifacts:/65/0157ba4a0db349b8b86e4a24592d9230/artifacts/Prostate - val"
    - "mlflow-artifacts:/65/0157ba4a0db349b8b86e4a24592d9230/artifacts/Prostate - test"
  percentage_cols: 
    - "carcinoma_roi_percentage"
    - "tissue_roi_percentage"
  tissue_threshold: 0.5

tiling:
  level: 1
  tile_extent: 512
  stride: 256
  # We prefer taking masks from MLFlow
  qc_masks_uri: "mlflow-artifacts:/65/df5ccd31178549afb5e843b1ea0741a0/artifacts/qc_masks"
  tissue_masks_uri: "mlflow-artifacts:/65/4ea7cee809a2443389855facba548959/artifacts/tissue_masks"
  annotation_masks_uri: "mlflow-artifacts:/65/199141b76f90457fbf6183bd70a1e488/artifacts/annotation_masks"

annotation_masks:
  level: 5
  max_concurrent: 100
  output_path: ${prostate_cancer_path}/annot_masks

tissue_masks:
  level: 3
  max_concurrent: 100
  output_path: ${prostate_cancer_path}/tissue_masks

qc_masks:
  request_limit: 4
  request_timeout: 1260
  report_request_timeout: 240
  url: "http://rayservice-qc-serve-svc.rationai-jobs-ns.svc.cluster.local:8000/"
  mask_level: 3
  sample_level: 1
  output_path: ${prostate_cancer_path}/qc_masks

metadata:
  experiment_name: Prostate
  run_name: ???
  description: ???
