_target_: albumentations.Compose
p: 1.0 # default
transforms:
  - _target_: albumentations.RandomRotate90
    p: 0.75
  - _target_: albumentations.Flip
    p: 0.5  # default
  - _target_: albumentations.RandomGamma
    p: 0.5  # default
  - _target_: albumentations.RandomBrightnessContrast
    p: 0.5
  - _target_: albumentations.HueSaturationValue
    p: 0.5
  - _target_: albumentations.Normalize
    mean: 0.5
    std: 0.5
    max_pixel_value: 255
    p: 1.0  # default
