defaults:
  - datasets@train: embeddings/bag_of_embeddings_sl_labeled
  - datasets@val: embeddings/bag_of_embeddings_sl_labeled
  - datasets@test: embeddings/bag_of_embeddings_sl_labeled
  - datasets@predict: embeddings/bag_of_embeddings_unlabeled

  - samplers@sampler: bag_of_tiles_stratified_weighted_random

_target_: prostate_cancer.datamodule.ClassicBagOfTilesDataModule

batch_size: ???
num_workers: ???
