defaults:
  - datasets@train: images/labeled_with_processor
  - datasets@val: images/labeled_with_processor
  - datasets@test: images/labeled_with_processor
  - datasets@predict: images/unlabeled_with_processor

  - samplers@sampler: stratified_weighted_random

processor:
  _target_: transformers.ViTImageProcessor.from_pretrained
  pretrained_model_name_or_path: google/vit-base-patch16-224

train:
  processor: ${datamodule.processor}
  stratified_filter: true
val:
  processor: ${datamodule.processor}
  stratified_filter: true
test:
  processor: ${datamodule.processor}
  stratified_filter: false
predict:
  processor: ${datamodule.processor}

batch_size: ???
num_workers: ???
