defaults:
  - datasets@train: images/labeled
  - datasets@val: images/labeled
  - datasets@test: images/labeled
  - datasets@predict: images/unlabeled

  - transforms@default_transform: normalize
  - samplers@sampler: stratified_weighted_random

_target_: prostate_cancer.datamodule.TileDataModule

train:
  transforms: ??? # specified during the training (stain / non-stain augmentations)
  stratified_filter: true
  processor: null
val:
  transforms: ${datamodule.default_transform}
  stratified_filter: true
  processor: null
test:
  transforms: ${datamodule.default_transform}
  stratified_filter: false
  processor: null
predict:
  transforms: ${datamodule.default_transform}
  processor: null

batch_size: ???
num_workers: ???
