defaults:
  - datasets@train: embeddings/tile_labeled
  - datasets@val: embeddings/tile_labeled
  - datasets@test: embeddings/tile_labeled
  - datasets@predict: embeddings/tile_unlabeled

  - samplers@sampler: stratified_weighted_random

_target_: prostate_cancer.datamodule.TileDataModule

train:
  stratified_filter: true
val:
  stratified_filter: true
test:
  stratified_filter: false # want to test all the tiles

batch_size: ???
num_workers: ???
