defaults:
  - base
  - _self_

tile_threshold: 0.91
slide_max_threshold: 0.0
slide_mpm_threshold: 0.0

checkpoint: "mlflow-artifacts:/65/608505561d8c4b3d8aabb767a9c81c0e/artifacts/checkpoints/epoch=1-step=69448/checkpoint.ckpt"
model_name: "Google ViT"
