defaults:
  - base
  - _self_

tile_threshold: 0.44
slide_max_threshold: 0.9540096521
slide_mpm_threshold: 0.324303627
slide_top_k_threshold: 0.4309533238
slide_span_threshold: 0.5 # arbitrary - span predictions are binary

checkpoint: "mlflow-artifacts:/65/d9bd39a0207c4b9484ad92574c50b503/artifacts/checkpoints/epoch=0-step=13889/checkpoint.ckpt"
public_checkpoint: "mlflow-artifacts:/38/abde571304794242be0c1630b7bd16ce/artifacts/resnet50_checkpoint.ckpt"

model_name: "ResNet50"
slide_level_prediction_uris:
  mean_pool_max:
    mmci_sl_group_1: "mlflow-artifacts:/65/46a594a334ef4bbe9fdc7ba73250b12a/artifacts/tables/aggregated_predictions_corrected.json"
  max:
    mmci_sl_group_1: "mlflow-artifacts:/65/94561b6417ea4f888495fdcb799555e2/artifacts/tables/aggregated_predictions_corrected.json"
  top_k:
    mmci_sl_group_1: "mlflow-artifacts:/65/bcf0312c738c460381bde996e5cb93d8/artifacts/tables/aggregated_predictions_corrected.json"
  span:
    mmci_sl_group_1: "mlflow-artifacts:/65/ccd4a8001874439f8c860eefa5d41fbe/artifacts/tables/aggregated_predictions_corrected.json"
