defaults:
  - base_foundation
  - _self_

tile_threshold: 0.85
slide_threshold: 0.99

checkpoint: "mlflow-artifacts:/65/5e0c1d4699ca49c4938baf3c65e7f61c/artifacts/checkpoints/epoch=6-step=1176/checkpoint.ckpt"
model_name: "Virchow2 (Hybrid-MIL)"
