defaults:
  - base_foundation
  - _self_

tile_threshold: 0.8
slide_max_threshold: 0.9993972778

checkpoint: "mlflow-artifacts:/65/d39c26e7dd474d3bbdd3932f6f8bf2fb/artifacts/checkpoints/epoch=0-step=27778/checkpoint.ckpt"
public_checkpoint: null

model_name: "Virchow2 (Stain & Frozen)"

slide_level_prediction_uris:
  mean_pool_max:
    mmci_sl_group_1: null
  max:
    mmci_sl_group_1: "mlflow-artifacts:/65/0356850470b4450bb24d426a7074f224/artifacts/tables/aggregated_predictions.json"
  top_k:
    mmci_sl_group_1: null
  span:
    mmci_sl_group_1: null
