# @package _global_

level: 5
max_concurrent: 100
output_path: ${prostate_cancer_path}/annot_masks_${data_name}

metadata:
  run_name: Annotation Masks ${data_name}
  description: Annotation Masks ${data_name}
