# @package _global_

batch_size: 128
output_path: ${prostate_cancer_path}/tile_embeddings_${data_name}

# Assuming the uri is is structured as: "mlflow-artifacts:/experiment_id/run_id/artifacts/Prostate - <partition>"
uris: []

metadata:
  run_name: PGP Embeddings ${data_name}
  description: PGP Embeddings ${data_name}
