# @package _global_

level: 3
max_concurrent: 100
output_path: ${prostate_cancer_path}/tissue_masks_${data_name}

metadata:
  run_name: Tissue Masks ${data_name}
  description: Annotation Masks ${data_name}
