# @package _global_
defaults:
  - base
  - _self_

t: ???

metadata:
  run_name: ${model_name} Slide-Level Predictions Table ${data_name}
  description: ${model_name} Slide-Level Predictions Table ${data_name}
