# @package _global_
defaults:
  - /default
  - _self_

table_uris:
  pgp: "mlflow-artifacts:/65/7c14fc3fdf2f448d906a1564acc42f55/artifacts/tables/sl_preds.csv"
  resnet50: "mlflow-artifacts:/65/43568199e1e44a1a8c260ee99843b05f/artifacts/tables/sl_preds.csv"
  resnet50_stain: "mlflow-artifacts:/65/cc86e734fa1c43d4909e232663ed4e6c/artifacts/tables/sl_preds.csv"
  vgg16: "mlflow-artifacts:/65/f5a205c517fa4c8b9e33b42d8cc51d69/artifacts/tables/sl_preds.csv"
  vgg16_stain: "mlflow-artifacts:/65/cc514d18a9c948acbcf7ce35c0b1e21d/artifacts/tables/sl_preds.csv"

metadata:
  run_name: Slide-Level Predictions Merged Table 
  description: Slide-Level Predictions Merged Table
